INSERT INTO teams(TeamID, Name, City, Conference, Division, WikipediaLogoUrl)
values
(
1,
"Washington",
"Wizards",
"Eastern",
"Southeast",
"https://upload.wikimedia.org/wikipedia/en/0/02/Washington_Wizards_logo.svg"
),
(
2,
"Charlotte",
"Hornets",
"Eastern",
"Southeast",
"https://upload.wikimedia.org/wikipedia/en/c/c4/Charlotte_Hornets_%282014%29.svg"
),
(
3,
"Atlanta",
"Hawks",
"Eastern",
"Southeast",
"https://upload.wikimedia.org/wikipedia/en/2/24/Atlanta_Hawks_logo.svg"
),
(
4,
"Miami",
"Heat",
"Eastern",
"Southeast",
"https://upload.wikimedia.org/wikipedia/en/f/fb/Miami_Heat_logo.svg"
),
(
5,
"Orlando",
"Magic",
"Eastern",
"Southeast",
"https://upload.wikimedia.org/wikipedia/en/1/10/Orlando_Magic_logo.svg"

),
(
6,
"New York",
"Knicks",
"Eastern",
"Atlantic",
"https://upload.wikimedia.org/wikipedia/en/2/25/New_York_Knicks_logo.svg"
),
(
7,
"Philadelphia",
"76ers",
"Eastern",
"Atlantic",
"https://upload.wikimedia.org/wikipedia/en/0/0e/Philadelphia_76ers_logo.svg"
),
(
8,
"Brooklyn",
"Nets",
"Eastern",
"Atlantic",
"https://upload.wikimedia.org/wikipedia/commons/4/44/Brooklyn_Nets_newlogo.svg"
),
(
9,
"Boston",
"Celtics",
"Eastern",
"Atlantic",
"https://upload.wikimedia.org/wikipedia/en/8/8f/Boston_Celtics.svg"
),
(
10,
"Toronto",
"Raptors",
"Eastern",
"Atlantic",
"https://upload.wikimedia.org/wikipedia/en/3/36/Toronto_Raptors_logo.svg"
),
(
11,
"Chicago",
"Bulls",
"Eastern",
"Central",
"https://upload.wikimedia.org/wikipedia/en/6/67/Chicago_Bulls_logo.svg"
),
(
12,
"Cleveland",
"Cavaliers",
"Eastern",
"Central",
"https://upload.wikimedia.org/wikipedia/en/4/4b/Cleveland_Cavaliers_logo.svg"
),
(
13,
"Indiana",
"Pacers",
"Eastern",
"Central",
"https://upload.wikimedia.org/wikipedia/en/1/1b/Indiana_Pacers.svg"
),
(
14,

"Detroit",
"Pistons",

"Eastern",
"Central",
"https://upload.wikimedia.org/wikipedia/commons/7/7c/Pistons_logo17.svg"
),
(
15,
"Milwaukee",
"Bucks",
"Eastern",
"Central",
"https://upload.wikimedia.org/wikipedia/en/4/4a/Milwaukee_Bucks_logo.svg"
),
(
16,
"Minnesota",
"Timberwolves",
"Western",
"Northwest",
"https://upload.wikimedia.org/wikipedia/en/c/c2/Minnesota_Timberwolves_logo.svg"
),
(
17,
"Utah",
"Jazz",
"Western",
"Northwest",
"https://upload.wikimedia.org/wikipedia/en/0/04/Utah_Jazz_logo_%282016%29.svg"
),
(
18,
"Oklahoma City",
"Thunder",
"Western",
"Northwest",
"https://upload.wikimedia.org/wikipedia/en/5/5d/Oklahoma_City_Thunder.svg"
),
(
19,
"Portland",
"Trail Blazers",
"Western",
"Northwest",
"https://upload.wikimedia.org/wikipedia/en/2/21/Portland_Trail_Blazers_logo.svg"
),
(
20,
"Denver",
"Nuggets",
"Western",
"Northwest",
"https://upload.wikimedia.org/wikipedia/en/7/76/Denver_Nuggets.svg"
),
(
21,
"Memphis",
"Grizzlies",
"Western",
"Southwest",
"https://upload.wikimedia.org/wikipedia/en/f/f1/Memphis_Grizzlies.svg"
),
(
22,
"Houston",
"Rockets",
"Western",
"Southwest",
"https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Rockets.svg"
),
(
23,
"New Orleans",
"Pelicans",
"Western",
"Southwest",
"https://upload.wikimedia.org/wikipedia/en/0/0d/New_Orleans_Pelicans_logo.svg"
),
(
24,
"San Antonio",
"Spurs",
"Western",
"Southwest",
"https://upload.wikimedia.org/wikipedia/en/a/a2/San_Antonio_Spurs.svg"
),
(
25,
"Dallas",
"Mavericks",
"Western",
"Southwest",
"https://upload.wikimedia.org/wikipedia/en/9/97/Dallas_Mavericks_logo.svg"
),
(
26,
"Golden State",
"Warriors",
"Western",
"Pacific",
"https://upload.wikimedia.org/wikipedia/en/0/01/Golden_State_Warriors_logo.svg"
),
(
27,
"Los Angeles",
"Lakers",
"Western",
"Pacific",
"https://upload.wikimedia.org/wikipedia/commons/3/3c/Los_Angeles_Lakers_logo.svg"
),
(
28,
"Los Angeles",
"Clippers",
"Western",
"Pacific",
"https://upload.wikimedia.org/wikipedia/en/b/bb/Los_Angeles_Clippers_%282015%29.svg"
),
(
29,
"Phoenix",
"Suns",
"Western",
"Pacific",
"https://upload.wikimedia.org/wikipedia/en/d/dc/Phoenix_Suns_logo.svg"
),
(
30,
"Sacramento",
"Kings",
"Western",
"Pacific",
"https://upload.wikimedia.org/wikipedia/en/c/c7/SacramentoKings.svg"
)